const towerData = {
  version: "1.0.0",
  data: [
    {
      id: 1,
      atckSpead: 6,
      atck: 1,
      upgrade: 0,
      upgradeValue: 4,
      range: 300,
      price: 200,
    },
    {
      id: 2,
      atckSpead: 5,
      atck: 2,
      upgrade: 0,
      upgradeValue: 2,
      range: 300,
      price: 400,
    },
    {
      id: 3,
      atckSpead: 6,
      atck: 3,
      upgrade: 0,
      upgradeValue: 3,
      range: 300,
      price: 600,
    },
    {
      id: 4,
      atckSpead: 5,
      atck: 4,
      upgrade: 0,
      upgradeValue: 2,
      range: 300,
      price: 800,
    },
    {
      id: 5,
      atckSpead: 2,
      atck: 1,
      upgrade: 0,
      upgradeValue: 4,
      range: 300,
      price: 1000,
    },
  ],
};
export default towerData;
